services:
  wonderwall:
    build: .
    environment:
      DNS_A_RECORD_IP: 172.128.0.128
    networks:
      default: {}
      internal:
        ipv4_address: 172.128.0.128

  curl:
    image: curlimages/curl
    command: sleep infinity
    networks:
      - internal
    dns:
      - 172.128.0.128

networks:
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.128.0.0/24
