services:
  wonderwall:
    build: .
    environment:
      DNS_A_RECORD_IP: ${WONDERWALL_IP:-172.128.0.128}
      ALLOWED_HOSTS: "*.google.com,google.com,*.httpbin.org,httpbin.org"
    networks:
      default: {}
      internal:
        ipv4_address: ${WONDERWALL_IP:-172.128.0.128}

  curl:
    image: curlimages/curl
    command: sleep infinity
    networks:
      - internal
    dns:
      - ${WONDERWALL_IP:-172.128.0.128}

networks:
  internal:
    internal: true
    ipam:
      config:
        - subnet: ${INTERNAL_SUBNET:-172.128.0.0/24}
